name: 12 Saatlik M3U Guncelleme

on:
  schedule:
    - cron: '0 */12 * * *' # Her 12 saatte bir çalışır
  workflow_dispatch: # Manuel olarak başlatma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle
        run: |
          pip install -r requirements.txt

      - name: Botu Çalıştır
        run: python scraper.py

      - name: Değişiklikleri Kaydet ve Pushla
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add deathless-xsportv.m3u
          git commit -m "M3U Listesi Güncellendi: $(date)" || exit 0
          git push
